#management endpoints on a separate port
management:
  endpoint:
    info:
      enabled: true

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false

  # ===============================
  # = Mysql configurations
  # ===============================
  datasource:
    url: jdbc:mysql://localhost:3306/rediscache?useUnicode=true&characterEncoding=UTF8&useSSL=false
    username: root
    password: 

  # ===============================
  # = Redis configurations
  # ===============================ß
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 5
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 3000

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.hackathon.carems: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    org:
      hibernate.SQL: DEBUG
      hibernate.type.descriptor.sql.BasicBinder: TRACE